package com.walkmate.data.mapper;

import com.walkmate.data.datasource.local.entity.RoutePointEntity;
import com.walkmate.data.datasource.remote.dto.request.tracking.PushRoutePointsRequest;
import com.walkmate.domain.tracking.RoutePoint;

import java.util.ArrayList;
import java.util.List;

/**
 * Bidirectional mapper between {@link RoutePointEntity} (Room) and
 * {@link RoutePoint} (domain), plus a helper to build the remote push payload.
 *
 * All methods are pure functions — no side effects, no Android context needed.
 */
public class RoutePointMapper {

    private RoutePointMapper() {}

    // ── Entity → Domain ───────────────────────────────────────────────────────

    public static RoutePoint toDomain(RoutePointEntity entity) {
        return new RoutePoint(
                entity.id,
                entity.sessionId,
                entity.lat,
                entity.lng,
                entity.timestamp,
                entity.accuracy,
                entity.isSynced
        );
    }

    public static List<RoutePoint> toDomainList(List<RoutePointEntity> entities) {
        List<RoutePoint> result = new ArrayList<>(entities.size());
        for (RoutePointEntity e : entities) {
            result.add(toDomain(e));
        }
        return result;
    }

    // ── Domain → Entity ───────────────────────────────────────────────────────

    public static RoutePointEntity toEntity(RoutePoint domain) {
        RoutePointEntity entity = new RoutePointEntity();
        // id is auto-generated by Room; only set for existing rows (id > 0)
        entity.id = domain.getId();
        entity.sessionId = domain.getSessionId();
        entity.lat = domain.getLat();
        entity.lng = domain.getLng();
        entity.timestamp = domain.getTimestamp();
        entity.accuracy = domain.getAccuracy();
        entity.isSynced = domain.isSynced();
        return entity;
    }

    // ── Entity → Remote DTO payload ───────────────────────────────────────────

    public static PushRoutePointsRequest.RoutePointPayload toPayload(RoutePointEntity entity) {
        return new PushRoutePointsRequest.RoutePointPayload(
                entity.id,
                entity.lat,
                entity.lng,
                entity.timestamp,
                entity.accuracy
        );
    }

    public static List<PushRoutePointsRequest.RoutePointPayload> toPayloadList(
            List<RoutePointEntity> entities) {
        List<PushRoutePointsRequest.RoutePointPayload> result = new ArrayList<>(entities.size());
        for (RoutePointEntity e : entities) {
            result.add(toPayload(e));
        }
        return result;
    }
}
