package com.walkmate.infrastructure.exception;

public enum ErrorCode {
  SESSION_NOT_FOUND,
  SESSION_INVALID_TRANSITION,
  SESSION_WINDOW_CLOSED,
  SESSION_NOT_PARTICIPANT,
  SESSION_MIN_DURATION_NOT_REACHED,
  SESSION_INVALID_TRACKING,
  SESSION_CONFLICT,
  SESSION_INVALID_COORDINATE,

  // Intent Errors
  INTENT_NOT_FOUND,
  INTENT_INVALID_TRANSITION,
  INTENT_INVALID_TIME_WINDOW,
  INTENT_INVALID_COORDINATE,
  INTENT_CONFLICT
}
