package com.walkmate.infrastructure.exception;

public enum ErrorCode {
    SESSION_INVALID_TRANSITION,
    SESSION_ALREADY_CANCELLED,
    SESSION_ACTIVATION_WINDOW_CLOSED,
    SESSION_TOO_SHORT_TO_COMPLETE,
    SESSION_USER_NOT_PARTICIPANT,
    SESSION_NOT_FOUND
}
