package com.walkmate.domain.rating;


public enum RatingErrorCode {
    RATING_INVALID_SCORE,
    RATING_SESSION_NOT_FOUND,
    RATING_SESSION_NOT_COMPLETED,
    RATING_ALREADY_EXISTS,
    RATING_UNAUTHORIZED,
    NETWORK_ERROR,
    UNKNOWN_ERROR
}
