##==============================
# ENVIRONMENT VARIABLES
# ==============================
# Automatically loaded by spring-dotenv library

# ==============================
# DATASOURCE (Supabase)
# ==============================
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xnsryuyrkehzbxejiwlk
spring.datasource.password=0n62W6ACHBVdi52b
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JOOQ
# ==============================
spring.jooq.sql-dialect=postgres

# ==============================
# LOGGING & TRACING CONFIG
# ==============================
# Logging Level
logging.level.com.walkmate=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.jooq.tools.LoggerListener=DEBUG
