##==============================
# ENVIRONMENT VARIABLES
# ==============================
# Automatically loaded by spring-dotenv library

# ==============================
# DATASOURCE (Supabase)
# ==============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JOOQ
# ==============================
spring.jooq.sql-dialect=postgres

# ==============================
# LOGGING & TRACING CONFIG
# ==============================
# Logging Level
logging.level.com.walkmate=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.jooq.tools.LoggerListener=DEBUG
